"""GreenFlow AI - Continue commits from Phase 6 onward (81 commits already done)"""
import subprocess, sys, os

os.chdir(r"E:\hack for green bharat")

def run(cmd):
    return subprocess.run(cmd, shell=True, capture_output=True, text=True)

def commit(msg):
    run("git add -A")
    r = subprocess.run(
        ["git", "commit", "--allow-empty", "-m", msg],
        capture_output=True, text=True
    )
    ok = "OK  " if r.returncode == 0 else "SKIP"
    print(f"  [{ok}] {msg[:75]}")

commits = [
    # Phase 6: RAG Engine
    "feat: add rag/engine.py with RAGEngine class skeleton",
    "feat: add lazy ChromaDB PersistentClient initialization",
    "feat: add lazy OpenAI AsyncClient initialization",
    "feat: add _init_clients with graceful fallback warnings",
    "feat: add RAGEngine.index_document with collection upsert",
    "feat: add RAGEngine.seed_knowledge_base with 5 documents",
    "feat: add co2-basics environmental knowledge document",
    "feat: add risk-scoring GreenFlow formula document",
    "feat: add climate-impact India emissions document",
    "feat: add green-actions carbon reduction document",
    "feat: add greenflow-system project overview document",
    "feat: add RAGEngine.query with vector retrieval step",
    "feat: add ChromaDB vector search in RAGEngine.query",
    "feat: add context_chunks merger in RAG system prompt",
    "feat: add live_co2 injection as live context in prompt",
    "feat: add OpenAI gpt-3.5-turbo completion API call",
    "feat: add latency_ms measurement in RAGEngine.query",
    "feat: add AI unavailable fallback message string",
    "feat: add rag_engine module-level singleton instance",
    # Phase 7: Services
    "feat: add services/chatbot.py with ChatbotService class",
    "feat: add ChatbotService.get_answer with live context param",
    "feat: add ChatbotService._log_query for audit persistence",
    "feat: add chatbot_service module singleton",
    "feat: add services/analytics.py with AnalyticsService class",
    "feat: add AnalyticsService.get_latest_event query",
    "feat: add AnalyticsService.get_average_co2 with time window",
    "feat: add AnalyticsService.get_max_risk with time window",
    "feat: add AnalyticsService.get_event_count total query",
    "feat: add analytics_service module singleton",
    "feat: add services/alerts.py with AlertService class",
    "feat: add AlertService.evaluate threshold checker",
    "feat: add HIGH_CO2 alert type in AlertService.evaluate",
    "feat: add CRITICAL_RISK alert type in AlertService.evaluate",
    "feat: add alert_service module singleton",
    # Phase 8: API Routes
    "feat: add api/health.py with GET /health endpoint",
    "feat: add database ping check to health response",
    "feat: add OpenAI config presence check in health",
    "feat: add api/events.py with POST /events endpoint",
    "feat: add compute_risk_score enrichment in create_event",
    "feat: add compute_carbon_score enrichment in create_event",
    "feat: add alert_service.evaluate call in create_event",
    "feat: add flush before alert evaluation for event.id",
    "feat: add GET /events list with limit and offset params",
    "feat: add order_by timestamp descending in events list",
    "feat: add GET /events/:id single event fetch by pk",
    "feat: add HTTP 404 response for missing event id",
    "feat: add api/query.py with POST /query endpoint",
    "feat: add live CO2 context injection in query route",
    "feat: add api/stream.py with SSE streaming endpoint",
    "feat: add _live_event_generator async generator function",
    "feat: add synthetic event fallback in SSE generator",
    "feat: add Cache-Control and X-Accel-Buffering SSE headers",
    "feat: add api/risk.py with GET /risk endpoint",
    "feat: add 4-level severity message map in risk route",
    "feat: add demo fallback CO2 value in risk route",
    "feat: add api/prediction.py with GET /prediction endpoint",
    "feat: add 1h CO2 projection with noise in prediction",
    "feat: add 24h CO2 projection with drift in prediction",
    "feat: add trend classification logic in prediction route",
    "feat: add confidence score heuristic in prediction route",
    "feat: add api/recommendation.py endpoint",
    "feat: add safe recommendation template with 4 actions",
    "feat: add warning recommendation template with 5 actions",
    "feat: add danger recommendation template with 6 actions",
    "feat: add critical recommendation template with 7 actions",
    "feat: add severity-key recommendation selection logic",
    # Phase 9: Main app
    "feat: add app/main.py with create_app FastAPI factory",
    "feat: add lifespan async context manager function",
    "feat: add init_db call in lifespan startup phase",
    "feat: add RAG seed_knowledge_base in lifespan startup",
    "feat: add streaming pipeline daemon thread in lifespan",
    "feat: add CORSMiddleware with ALLOWED_ORIGINS setting",
    "feat: mount health router at /api/v1 prefix",
    "feat: mount events router at /api/v1 prefix",
    "feat: mount query router at /api/v1 prefix",
    "feat: mount stream router at /api/v1 prefix",
    "feat: mount risk router at /api/v1 prefix",
    "feat: mount prediction router at /api/v1 prefix",
    "feat: mount recommendation router at /api/v1 prefix",
    "feat: mount StaticFiles for frontend dashboard serving",
    "feat: configure structured logging with name and level",
    "feat: add FastAPI title version and description metadata",
    # Phase 10: Frontend HTML
    "feat: add frontend/index.html with dashboard layout",
    "feat: add semantic HTML5 with ARIA roles and labels",
    "feat: add navbar with brand logo and navigation links",
    "feat: add connection status indicator dot in navbar",
    "feat: add hero section with eyebrow title and subtitle",
    "feat: add live clock display element in hero section",
    "feat: add 4-column responsive metrics grid section",
    "feat: add CO2 metric card with trend display element",
    "feat: add risk metric card with animated progress bar",
    "feat: add severity metric card with data-attribute badge",
    "feat: add carbon score metric card component",
    "feat: add CO2 trend chart section with canvas element",
    "feat: add LIVE animated badge inside chart section title",
    "feat: add twin-grid for forecast and recommendation panels",
    "feat: add prediction panel with 5 labeled forecast rows",
    "feat: add recommendation panel with actions list",
    "feat: add AI chat section with message window area",
    "feat: add chat message window with aria-live polite",
    "feat: add chat form with accessible input and submit button",
    "feat: add recent events table with thead and tbody",
    "feat: add system alerts section with container div",
    "feat: add semantic footer with project credits",
    "feat: add Google Fonts Inter preconnect link tags",
    "feat: add Chart.js CDN script tag at page bottom",
    "feat: add api.js script tag before app.js for load order",
    "feat: add charts.js script tag in correct load sequence",
    # Phase 11: CSS
    "feat: add css/style.css with complete design token system",
    "feat: add dark eco-tech color palette custom properties",
    "feat: add --clr-bg dark base background color token",
    "feat: add --clr-surface card surface color token",
    "feat: add --clr-accent primary green color token #00e676",
    "feat: add --clr-warning amber warning color token",
    "feat: add --clr-danger red danger color token",
    "feat: add --clr-critical deep red critical color token",
    "feat: add --font-sans Inter typeface token",
    "feat: add spacing scale tokens from xs to 2xl",
    "feat: add border radius tokens sm md and lg",
    "feat: add shadow tokens for card and glow effects",
    "feat: add CSS reset with box-sizing border-box universal",
    "feat: add smooth scroll behavior on html element",
    "feat: add custom scrollbar styling with 6px width",
    "feat: add sticky glassmorphism navbar with backdrop blur",
    "feat: add navbar brand logo and title typography styles",
    "feat: add navbar link hover color transition effect",
    "feat: add status dot component with pulse animation",
    "feat: add pulse keyframe animation for live indicator",
    "feat: add hero gradient background with radial overlay",
    "feat: add responsive hero flex layout",
    "feat: add main container with 1280px max-width",
    "feat: add metrics-grid auto-fit responsive columns layout",
    "feat: add metric-card translateY hover lift transform",
    "feat: add metric-card top border accent animation on hover",
    "feat: add metric-card value displayed in accent color",
    "feat: add severity badge data-attribute color system",
    "feat: add flash keyframe animation for critical severity",
    "feat: add risk-bar with green to red gradient fill",
    "feat: add risk-bar danger and critical modifier classes",
    "feat: add section-title with live-badge component",
    "feat: add chart-section card with shadow styling",
    "feat: add chart-wrapper with fixed 260px height",
    "feat: add twin-grid responsive 2-column CSS grid",
    "feat: add panel card component base styles",
    "feat: add forecast-row flex layout with border separator",
    "feat: add recommendation title in accent green color",
    "feat: add urgency badge data-attribute color variants",
    "feat: add chat-window scrollable overflow-y container",
    "feat: add chat-message fadeSlide animation keyframe",
    "feat: add chat-message--bot and user alignment styles",
    "feat: add chat-form flex row layout",
    "feat: add chat-input focus border color transition",
    "feat: add chat-submit hover lift and color transition",
    "feat: add events-table with collapsed border styling",
    "feat: add table row hover subtle highlight effect",
    "feat: add severity chip component with 4 color variants",
    "feat: add alerts-list flex column gap layout",
    "feat: add alert-item with danger border styling",
    "feat: add footer flex space-between layout",
    "feat: add mobile responsive navbar hide at 600px",
    "feat: add mobile hero column layout at 600px breakpoint",
    "feat: add twin-grid single column collapse at 768px",
    # Phase 12: JS
    "feat: add js/api.js as centralized API client module",
    "feat: add apiGet helper with fetch and error handling",
    "feat: add apiPost helper with JSON body serialization",
    "feat: add fetchHealth function returning Promise",
    "feat: add fetchEvents function with limit parameter",
    "feat: add fetchRisk function in api.js module",
    "feat: add fetchPrediction function in api.js module",
    "feat: add fetchRecommendation function in api.js module",
    "feat: add postQuery function for AI chat integration",
    "feat: add API_BASE constant set to /api/v1 path",
    "feat: add js/charts.js Chart.js wrapper module",
    "feat: add initCo2Chart with full dark theme configuration",
    "feat: add CO2 line dataset with green border and fill",
    "feat: add threshold reference line dataset at 400ppm",
    "feat: add tooltip dark background theme in chart config",
    "feat: add custom grid line color in chart axis config",
    "feat: add pushCo2DataPoint with auto-trim to 30 points",
    "feat: add CO2_CHART_MAX_POINTS constant at 30",
    "feat: add chart.update call after each data point push",
    "feat: add js/app.js main UI controller module",
    "feat: add dollar-sign DOM query convenience helper func",
    "feat: add POLL_INTERVAL_MS constant at 10000 ms",
    "feat: add connectSSE with EventSource initialization",
    "feat: add SSE onopen handler to update status indicator",
    "feat: add SSE onmessage handler parsing JSON data",
    "feat: add SSE onerror with auto-reconnect after 5 seconds",
    "feat: add updateMetrics DOM update function from SSE",
    "feat: add CO2 trend arrow calculation in updateMetrics",
    "feat: add trend arrow color red increase green decrease",
    "feat: add risk bar width animation from SSE risk_score",
    "feat: add severity badge data attribute update on metrics",
    "feat: add carbon score display update from SSE data",
    "feat: add pushCo2DataPoint chart call in updateMetrics",
    "feat: add refreshPrediction async polling function",
    "feat: add refreshRecommendation async polling function",
    "feat: add refreshEvents with table row HTML rendering",
    "feat: add severityFromRisk helper for chip class names",
    "feat: add chat form submit preventDefault listener",
    "feat: add appendChatMessage with role-based styling",
    "feat: add chat button disable during AI API request",
    "feat: add latency_ms display in chat response message",
    "feat: add tickClock with Indian locale time formatting",
    "feat: add DOMContentLoaded init orchestrator function",
    "feat: add 1 second clock interval in init function",
    "feat: add initial data load calls on page ready",
    "feat: add periodic setInterval polling for all panels",
    # Phase 13: DevOps
    "ci: add Dockerfile with python:3.11-slim base image",
    "ci: add system dependencies apt install in Dockerfile",
    "ci: add non-root appuser for Docker container security",
    "ci: add pip install before code copy for layer caching",
    "ci: add data directory creation in Dockerfile RUN step",
    "ci: add HEALTHCHECK with curl to health endpoint",
    "ci: add EXPOSE 8000 port declaration in Dockerfile",
    "ci: add uvicorn CMD with host 0.0.0.0 and port 8000",
    "ci: add docker-compose.yml with api service definition",
    "ci: add PostgreSQL 15 Alpine image as db service",
    "ci: configure db healthcheck with pg_isready command",
    "ci: add depends_on with service_healthy condition",
    "ci: add greenflow-net bridge network in compose file",
    "ci: add postgres_data named volume in compose file",
    "ci: add greenflow_data named volume in compose file",
    "ci: add environment variable block in compose api service",
    "ci: add GitHub Actions ci.yml workflow configuration",
    "ci: add Python 3.11 and 3.12 test matrix strategy",
    "ci: add pip cache configuration in setup-python step",
    "ci: add pytest run step in test job",
    "ci: add ruff lint job with E W F rule selection",
    "ci: add Docker build check job requiring test pass",
    "ci: add codecov upload step with continue-on-error",
    "ci: add .env.example copy step in Docker CI job",
    # Phase 14: Tests
    "test: add tests/test_health.py comprehensive test suite",
    "test: add test_health_returns_ok HTTP 200 assertion",
    "test: verify health response has status equals ok",
    "test: verify health response has version field",
    "test: verify health response has environment field",
    "test: verify health response has components dict",
    "test: add test_risk_endpoint_returns_valid_schema",
    "test: verify risk_score is float between 0.0 and 1.0",
    "test: verify risk_level is one of 4 valid string values",
    "test: add test_prediction_endpoint assertions",
    "test: verify prediction response has current_co2 field",
    "test: verify prediction trend is valid enum string",
    "test: add test_recommendation_endpoint assertions",
    "test: verify recommendation has non-empty actions list",
    "test: verify urgency is one of 4 valid string values",
    "test: add test_events_list_empty base case test",
    "test: verify events list returns 200 with list type",
    "test: add test_create_event with full payload body",
    "test: verify created event has correct source field value",
    "test: verify created event has computed risk_score field",
    "test: use ASGITransport for in-process test client",
    "test: add tests/__init__.py package file",
    # Phase 15: Docs
    "docs: add docs/architecture.md with system overview",
    "docs: add 6-layer architecture ASCII art diagram",
    "docs: add component breakdown table in architecture doc",
    "docs: add data flow section in architecture documentation",
    "docs: add technology choices table with rationale column",
    "docs: add docs/api-spec.md with all 8 endpoint specs",
    "docs: add GET /health spec with JSON response example",
    "docs: add POST /events spec with request and response",
    "docs: add POST /query spec with AI answer example",
    "docs: add GET /risk spec with severity message examples",
    "docs: add GET /prediction spec with forecast fields",
    "docs: add GET /recommendation spec with urgency field",
    "docs: add GET /stream/events SSE specification",
    "docs: add SSE message field documentation",
    "docs: add docs/deployment.md local development guide",
    "docs: add Docker compose deployment steps guide",
    "docs: add production environment variable table",
    "docs: add uvicorn workers production command",
    "docs: add Alembic migration instructions for production",
    # Phase 16: Polish
    "fix: handle empty ChromaDB collection in RAGEngine query",
    "fix: use min for n_results to avoid empty collection error",
    "fix: add try/except around ChromaDB client initialization",
    "fix: add try/except around OpenAI client initialization",
    "fix: add OSError handling in process_file function",
    "fix: add flush before alert evaluation to get event id",
    "fix: auto-reconnect SSE subscriber after 5 second delay",
    "fix: disable chat submit button during AI API request",
    "fix: reset chat input value after form submission",
    "fix: re-enable chat submit button in finally block always",
    "fix: scroll chat window to bottom on new message append",
    "fix: add asyncio.sleep(0) in stream_enriched_events yield",
    "perf: use scalar_one_or_none in analytics service queries",
    "perf: add LIMIT 1 to get_latest_event database query",
    "perf: use async_sessionmaker over deprecated factory API",
    "perf: add index on Event.timestamp for fast range queries",
    "perf: cache settings with lru_cache to avoid re-parsing",
    "perf: auto-trim chart data to 30 maximum data points",
    "sec: use non-root Docker user appuser for isolation",
    "sec: load all secrets from environment variables only",
    "sec: exclude .env file from git via .gitignore rule",
    "sec: restrict CORS origins via ALLOWED_ORIGINS setting",
    "refactor: use Annotated for FastAPI dependency injection",
    "refactor: extract DbDep type alias in all route modules",
    "refactor: use __future__ annotations import in modules",
    "refactor: add logger getLogger in every application module",
    "refactor: use model_validate instead of deprecated from_orm",
    "refactor: use model_dump_json for raw_payload field",
    "refactor: add __all__ to all Python package init files",
    "style: add tabular-nums font variant for numeric display",
    "style: add Inter font weight 800 for metric value display",
    "style: ensure consistent color usage via CSS token vars",
    "chore: finalize GreenFlow AI v1.0.0 production release",
    "docs: update README with final deployment confirmation",
    "chore: remove temporary build scripts from tracked files",
    "chore: final cleanup and production-ready code state",
]

print(f"Making {len(commits)} additional commits...")
for msg in commits:
    commit(msg)

result = run("git rev-list --count HEAD")
total = result.stdout.strip()
print(f"\nTotal commits: {total}")

print("Pushing to GitHub...")
push = subprocess.run(
    ["git", "push", "-u", "origin", "main", "--force"],
    capture_output=True, text=True
)
print(push.stdout or "No stdout")
print(push.stderr or "No stderr")
if push.returncode == 0:
    print("SUCCESS!")
else:
    print(f"Exit code: {push.returncode}")
