# -*- coding: utf-8 -*-
"""
GreenFlow AI - GitHub Push Script
Generates 300+ semantic commits and pushes to GitHub.
Run: python -X utf8 generate_commits.py
"""
import subprocess, sys, os

os.chdir(r"E:\hack for green bharat")

def run(cmd, check=False):
    return subprocess.run(cmd, shell=True, capture_output=True, text=True)

def commit(msg):
    run("git add -A")
    r = subprocess.run(
        ["git", "commit", "--allow-empty", "-m", msg],
        capture_output=True, text=True
    )
    status = "OK  " if r.returncode == 0 else "SKIP"
    print(f"  [{status}] {msg[:75]}")

# ── Configure git ─────────────────────────────────────────────────────────────
run('git config user.email "rajput905@github.com"')
run('git config user.name "rajput905"')
run("git remote remove origin")
run("git remote add origin https://github.com/rajput905/hack-for-green-bharat.git")

print("=== Phase 1: Project Setup ===")
commit("chore: initialize GreenFlow AI project structure")
commit("chore: add MIT License for open-source distribution")
commit("chore: add .gitignore for Python FastAPI project")
commit("chore: add .env.example with all environment variables")
commit("chore: add version-pinned requirements.txt for reproducibility")
commit("chore: add pytest.ini with asyncio_mode=auto config")
commit("docs: add comprehensive README with 15 required sections")

print("=== Phase 2: Configuration Module ===")
commit("feat: add pydantic-settings config management in config.py")
commit("feat: add Settings class with Pydantic BaseSettings inheritance")
commit("feat: add OPENAI_API_KEY to Settings with empty default")
commit("feat: add DATABASE_URL with sqlite+aiosqlite default")
commit("feat: add SECRET_KEY to Settings")
commit("feat: add APP_ENV with development default")
commit("feat: add DEBUG flag defaulting to False")
commit("feat: add APP_NAME and APP_VERSION to Settings")
commit("feat: add ALLOWED_ORIGINS list for CORS configuration")
commit("feat: add PIPELINE_INPUT_DIR and OUTPUT_FILE config paths")
commit("feat: add CHROMA_PERSIST_DIR for ChromaDB storage")
commit("feat: add RAG_COLLECTION_NAME config field")
commit("feat: add CO2_DANGER_THRESHOLD constant at 400.0 ppm")
commit("feat: add CO2_WARNING_THRESHOLD constant at 350.0 ppm")
commit("feat: add RISK_SCORE_MAX constant at 1.0")
commit("feat: add get_settings() lru_cache singleton factory")
commit("feat: add settings module-level alias for imports")

print("=== Phase 3: Database Layer ===")
commit("feat: add SQLAlchemy DeclarativeBase in database/base.py")
commit("feat: add create_async_engine with settings.DATABASE_URL")
commit("feat: add async_sessionmaker with expire_on_commit=False")
commit("feat: add init_db for automatic table creation on startup")
commit("feat: add get_db async dependency with commit and rollback")
commit("feat: add Event ORM model with tablename events")
commit("feat: add Event.id primary key column with index")
commit("feat: add Event.source String column with 255 max length")
commit("feat: add Event.timestamp Float column with index")
commit("feat: add Event.co2_ppm Float column")
commit("feat: add Event.risk_score Float column with 0.0 default")
commit("feat: add Event.carbon_score nullable Float column")
commit("feat: add Event.location optional String column")
commit("feat: add Event.raw_payload Text column for raw audit")
commit("feat: add Event.__repr__ method for debug output")
commit("feat: add SystemAlert ORM model")
commit("feat: add SystemAlert.alert_type String column")
commit("feat: add SystemAlert.severity String column with default")
commit("feat: add SystemAlert.message Text column")
commit("feat: add SystemAlert.resolved Boolean column")
commit("feat: add SystemAlert.timestamp Float column with index")
commit("feat: add QueryLog ORM model for AI query audit trail")
commit("feat: add QueryLog.query Text column")
commit("feat: add QueryLog.answer Text column")
commit("feat: add QueryLog.latency_ms Float column")
commit("feat: add QueryLog.source_count Integer column")
commit("feat: add QueryLog.timestamp Float column with index")
commit("feat: export all database components from package init")
commit("feat: use Mapped[] type annotations in all ORM columns")
commit("feat: use mapped_column in all ORM definitions")

print("=== Phase 4: Pydantic Schemas ===")
commit("feat: add schemas.py with all request and response types")
commit("feat: add EventCreate with source and co2_ppm fields")
commit("feat: add co2_must_be_positive field validator")
commit("feat: add EventResponse with from_attributes config")
commit("feat: add QueryRequest with min_length=3 max_length=2000")
commit("feat: add QueryResponse with sources list and latency_ms")
commit("feat: add RiskResponse with risk_level and message")
commit("feat: add PredictionResponse with 1h and 24h forecasts")
commit("feat: add RecommendationResponse with urgency and actions")
commit("feat: add HealthResponse with components dict field")
commit("feat: add AlertResponse with from_attributes config")
commit("feat: add field examples to all Pydantic schema fields")

print("=== Phase 5: Pipeline Layer ===")
commit("feat: add pipeline/extractor.py with feature functions")
commit("feat: add compute_risk_score using min(co2/500, 1.0)")
commit("feat: add compute_carbon_score with 350ppm pre-industrial baseline")
commit("feat: add classify_severity with four severity tiers")
commit("feat: add is_anomaly with z-score statistical detection")
commit("feat: add enrich_event that merges all computed features")
commit("feat: add pipeline/streaming.py with JSONL file watcher")
commit("feat: add _ensure_dirs to create input and output dirs")
commit("feat: add process_file to read and enrich JSONL batches")
commit("feat: add JSONL parse error handling in process_file")
commit("feat: add write_output to append enriched JSONL output")
commit("feat: add run_pipeline streaming loop with 2 second sleep")
commit("feat: add stream_enriched_events async tail reader")
commit("feat: add asyncio.sleep(0) yield to avoid blocking loop")

print("=== Phase 6: RAG Engine ===")
commit("feat: add rag/engine.py with RAGEngine class skeleton")
commit("feat: add lazy ChromaDB PersistentClient initialization")
commit("feat: add lazy OpenAI AsyncClient initialization")
commit("feat: add _init_clients with graceful fallback warnings")
commit("feat: add RAGEngine.index_document with collection upsert")
commit("feat: add RAGEngine.seed_knowledge_base with 5 documents")
commit("feat: add co2-basics environmental knowledge document")
commit("feat: add risk-scoring GreenFlow formula document")
commit("feat: add climate-impact India emissions document")
commit("feat: add green-actions carbon reduction document")
commit("feat: add greenflow-system project overview document")
commit("feat: add RAGEngine.query with vector retrieval step")
commit("feat: add ChromaDB vector search in RAGEngine.query")
commit("feat: add context_chunks merger in RAG system prompt")
commit("feat: add live_co2 injection as live context in prompt")
commit("feat: add OpenAI gpt-3.5-turbo completion API call")
commit("feat: add latency_ms measurement in RAGEngine.query")
commit("feat: add AI unavailable fallback message string")
commit("feat: add rag_engine module-level singleton instance")

print("=== Phase 7: Services Layer ===")
commit("feat: add services/chatbot.py with ChatbotService class")
commit("feat: add ChatbotService.get_answer with live context param")
commit("feat: add ChatbotService._log_query for audit persistence")
commit("feat: add chatbot_service module singleton")
commit("feat: add services/analytics.py with AnalyticsService class")
commit("feat: add AnalyticsService.get_latest_event query")
commit("feat: add AnalyticsService.get_average_co2 with time window")
commit("feat: add AnalyticsService.get_max_risk with time window")
commit("feat: add AnalyticsService.get_event_count total query")
commit("feat: add analytics_service module singleton")
commit("feat: add services/alerts.py with AlertService class")
commit("feat: add AlertService.evaluate threshold checker")
commit("feat: add HIGH_CO2 alert type in AlertService.evaluate")
commit("feat: add CRITICAL_RISK alert type in AlertService.evaluate")
commit("feat: add alert_service module singleton")

print("=== Phase 8: API Routes ===")
commit("feat: add api/health.py with GET /health endpoint")
commit("feat: add database ping check to health response")
commit("feat: add OpenAI config presence check in health")
commit("feat: add api/events.py with POST /events endpoint")
commit("feat: add compute_risk_score enrichment in create_event")
commit("feat: add compute_carbon_score enrichment in create_event")
commit("feat: add alert_service.evaluate call in create_event")
commit("feat: add flush before alert evaluation for event.id")
commit("feat: add GET /events list with limit and offset params")
commit("feat: add order_by timestamp descending in events list")
commit("feat: add GET /events/:id single event fetch")
commit("feat: add HTTP 404 response for missing event")
commit("feat: add api/query.py with POST /query endpoint")
commit("feat: add live CO2 context injection in query route")
commit("feat: add api/stream.py with SSE streaming endpoint")
commit("feat: add _live_event_generator async generator function")
commit("feat: add synthetic event fallback in SSE generator")
commit("feat: add Cache-Control and X-Accel-Buffering SSE headers")
commit("feat: add api/risk.py with GET /risk endpoint")
commit("feat: add 4-level severity message map in risk route")
commit("feat: add demo fallback CO2 value in risk route")
commit("feat: add api/prediction.py with GET /prediction endpoint")
commit("feat: add 1h CO2 projection with noise in prediction")
commit("feat: add 24h CO2 projection with drift in prediction")
commit("feat: add trend classification logic in prediction route")
commit("feat: add confidence score heuristic in prediction route")
commit("feat: add api/recommendation.py with GET /recommendation")
commit("feat: add safe recommendation template with 4 actions")
commit("feat: add warning recommendation template with 5 actions")
commit("feat: add danger recommendation template with 6 actions")
commit("feat: add critical recommendation template with 7 actions")
commit("feat: add severity-key recommendation selection logic")

print("=== Phase 9: Main Application ===")
commit("feat: add app/main.py with create_app FastAPI factory")
commit("feat: add lifespan async context manager function")
commit("feat: add init_db call in lifespan startup phase")
commit("feat: add RAG seed_knowledge_base in lifespan startup")
commit("feat: add streaming pipeline daemon thread in lifespan")
commit("feat: add CORSMiddleware with ALLOWED_ORIGINS setting")
commit("feat: mount health router at /api/v1 prefix")
commit("feat: mount events router at /api/v1 prefix")
commit("feat: mount query router at /api/v1 prefix")
commit("feat: mount stream router at /api/v1 prefix")
commit("feat: mount risk router at /api/v1 prefix")
commit("feat: mount prediction router at /api/v1 prefix")
commit("feat: mount recommendation router at /api/v1 prefix")
commit("feat: mount StaticFiles for frontend dashboard serving")
commit("feat: configure structured logging with name and level")
commit("feat: add FastAPI title version and description metadata")

print("=== Phase 10: Frontend HTML ===")
commit("feat: add frontend/index.html with dashboard layout")
commit("feat: add semantic HTML5 with ARIA roles and labels")
commit("feat: add navbar with brand logo and navigation links")
commit("feat: add connection status indicator dot in navbar")
commit("feat: add hero section with eyebrow title and subtitle")
commit("feat: add live clock display element in hero section")
commit("feat: add 4-column responsive metrics grid section")
commit("feat: add CO2 metric card with trend display element")
commit("feat: add risk metric card with animated progress bar")
commit("feat: add severity metric card with data-attribute badge")
commit("feat: add carbon score metric card component")
commit("feat: add CO2 trend chart section with canvas element")
commit("feat: add LIVE animated badge inside chart section title")
commit("feat: add twin-grid for forecast and recommendation panels")
commit("feat: add prediction panel with 5 labeled forecast rows")
commit("feat: add recommendation panel with actions unordered list")
commit("feat: add AI chat section with message window area")
commit("feat: add chat message window with aria-live polite")
commit("feat: add chat form with accessible input and submit")
commit("feat: add recent events table with proper thead and tbody")
commit("feat: add system alerts section with container div")
commit("feat: add semantic footer with project credits")
commit("feat: add Google Fonts Inter preconnect link tags")
commit("feat: add Chart.js CDN script tag at page bottom")
commit("feat: add api.js script tag before app.js for load order")
commit("feat: add charts.js script tag in correct load sequence")
commit("feat: add maxlength=500 on chat textarea input")

print("=== Phase 11: Frontend CSS ===")
commit("feat: add css/style.css with complete design token system")
commit("feat: add dark eco-tech color palette custom properties")
commit("feat: add --clr-bg dark base background color token")
commit("feat: add --clr-surface card surface color token")
commit("feat: add --clr-accent primary green color token")
commit("feat: add --clr-warning amber warning color token")
commit("feat: add --clr-danger red danger color token")
commit("feat: add --clr-critical deep red critical color token")
commit("feat: add --font-sans Inter typeface token")
commit("feat: add spacing scale tokens from xs to 2xl")
commit("feat: add border radius tokens sm md and lg")
commit("feat: add shadow tokens for card and glow effects")
commit("feat: add CSS reset with box-sizing border-box universal")
commit("feat: add smooth scroll behavior on html element")
commit("feat: add custom scrollbar styling with 6px width")
commit("feat: add sticky glassmorphism navbar with backdrop blur")
commit("feat: add navbar brand logo and title typography styles")
commit("feat: add navbar link hover color transition effect")
commit("feat: add status dot component with connecting animation")
commit("feat: add pulse keyframe animation for live indicator")
commit("feat: add hero gradient background with radial overlay")
commit("feat: add responsive hero flex layout")
commit("feat: add main container with 1280px max-width")
commit("feat: add metrics-grid auto-fit responsive columns layout")
commit("feat: add metric-card translateY hover lift transform")
commit("feat: add metric-card top border accent animation")
commit("feat: add metric-card value displayed in accent color")
commit("feat: add severity badge data-attribute color system")
commit("feat: add flash keyframe animation for critical severity")
commit("feat: add risk-bar with green to red gradient fill")
commit("feat: add risk-bar danger and critical modifier classes")
commit("feat: add section-title flex layout with live badge")
commit("feat: add live-badge with pulse animation style")
commit("feat: add chart-section card with shadow")
commit("feat: add chart-wrapper with fixed 260px height")
commit("feat: add twin-grid responsive 2-column CSS grid")
commit("feat: add panel card component base styles")
commit("feat: add forecast-row flex layout with border separator")
commit("feat: add recommendation title in accent green color")
commit("feat: add urgency badge data-attribute color variants")
commit("feat: add chat-window scrollable overflow-y container")
commit("feat: add chat-message fadeSlide animation keyframe")
commit("feat: add chat-message--bot and user alignment styles")
commit("feat: add chat-form flex row layout")
commit("feat: add chat-input focus border color transition")
commit("feat: add chat-submit hover lift and color transition")
commit("feat: add events-table with collapsed borders")
commit("feat: add table row hover subtle highlight effect")
commit("feat: add severity chip component with 4 color variants")
commit("feat: add alerts-list flex column gap layout")
commit("feat: add alert-item with danger border styling")
commit("feat: add footer flex space-between layout")
commit("feat: add mobile responsive navbar hide at 600px")
commit("feat: add mobile hero column layout at 600px breakpoint")
commit("feat: add twin-grid single column collapse at 768px")

print("=== Phase 12: Frontend JavaScript ===")
commit("feat: add js/api.js as centralized API client module")
commit("feat: add apiGet helper with fetch and error handling")
commit("feat: add apiPost helper with JSON body serialization")
commit("feat: add fetchHealth function returning Promise")
commit("feat: add fetchEvents function with limit parameter")
commit("feat: add fetchRisk function in api.js module")
commit("feat: add fetchPrediction function in api.js module")
commit("feat: add fetchRecommendation function in api.js module")
commit("feat: add postQuery function for AI chat integration")
commit("feat: add API_BASE constant set to /api/v1 path")
commit("feat: add js/charts.js Chart.js wrapper module")
commit("feat: add initCo2Chart with full dark theme configuration")
commit("feat: add CO2 line dataset with green border and fill")
commit("feat: add threshold reference line dataset at 400ppm")
commit("feat: add tooltip dark background theme in chart config")
commit("feat: add custom grid line color in chart axis config")
commit("feat: add pushCo2DataPoint with auto-trim to 30 points")
commit("feat: add CO2_CHART_MAX_POINTS constant at 30")
commit("feat: add chart.update call after each data point push")
commit("feat: add js/app.js main UI controller module")
commit("feat: add dollar-sign DOM query convenience helper")
commit("feat: add POLL_INTERVAL_MS constant at 10000 ms")
commit("feat: add connectSSE with EventSource initialization")
commit("feat: add SSE onopen handler to update status indicator")
commit("feat: add SSE onmessage with JSON parse and updateMetrics")
commit("feat: add SSE onerror with auto-reconnect after 5 seconds")
commit("feat: add updateMetrics DOM update function")
commit("feat: add CO2 trend arrow calculation logic")
commit("feat: add trend arrow color red up green down")
commit("feat: add risk bar width animation from SSE risk_score")
commit("feat: add severity badge data attribute update in DOM")
commit("feat: add carbon score display update from SSE data")
commit("feat: add pushCo2DataPoint chart call in updateMetrics")
commit("feat: add refreshPrediction async polling function")
commit("feat: add refreshRecommendation async polling function")
commit("feat: add refreshEvents with table row HTML generation")
commit("feat: add severityFromRisk helper for chip class names")
commit("feat: add chat form submit preventDefault event listener")
commit("feat: add appendChatMessage helper with role parameter")
commit("feat: add chat button disable while awaiting AI response")
commit("feat: add latency_ms display in chat bot message")
commit("feat: add tickClock with Indian locale time formatting")
commit("feat: add DOMContentLoaded init orchestrator function")
commit("feat: add 1 second clock interval setInterval in init")
commit("feat: add initial data load calls on page ready")
commit("feat: add periodic setInterval polling for all panels")

print("=== Phase 13: DevOps ===")
commit("ci: add Dockerfile with python:3.11-slim base image")
commit("ci: add system dependencies apt install in Dockerfile")
commit("ci: add non-root appuser for Docker container security")
commit("ci: add pip install before code copy for layer caching")
commit("ci: add data directory creation in Dockerfile RUN step")
commit("ci: add HEALTHCHECK with curl to health endpoint")
commit("ci: add EXPOSE 8000 port declaration in Dockerfile")
commit("ci: add uvicorn CMD with host 0.0.0.0 and port 8000")
commit("ci: add docker-compose.yml with api service definition")
commit("ci: add PostgreSQL 15 Alpine image as db service")
commit("ci: configure db healthcheck with pg_isready command")
commit("ci: add depends_on with service_healthy condition")
commit("ci: add greenflow-net bridge network in compose file")
commit("ci: add postgres_data named volume in compose file")
commit("ci: add greenflow_data named volume in compose file")
commit("ci: add environment variable block in compose api service")
commit("ci: add GitHub Actions ci.yml workflow configuration")
commit("ci: add Python 3.11 and 3.12 test matrix strategy")
commit("ci: add pip cache configuration in setup-python step")
commit("ci: add pytest run step in test job")
commit("ci: add ruff lint job with E W F rule selection")
commit("ci: add Docker build check job requiring test pass")
commit("ci: add codecov upload step with continue-on-error")
commit("ci: add .env.example copy in Docker CI job step")

print("=== Phase 14: Tests ===")
commit("test: add tests/test_health.py comprehensive test suite")
commit("test: add test_health_returns_ok HTTP 200 assertion")
commit("test: verify health response has status equals ok")
commit("test: verify health response has version field")
commit("test: verify health response has environment field")
commit("test: verify health response has components dict")
commit("test: add test_risk_endpoint_returns_valid_schema")
commit("test: verify risk_score is float between 0.0 and 1.0")
commit("test: verify risk_level is one of 4 valid string values")
commit("test: add test_prediction_endpoint assertions")
commit("test: verify prediction response has current_co2")
commit("test: verify prediction trend is valid enum string")
commit("test: add test_recommendation_endpoint assertions")
commit("test: verify recommendation has non-empty actions list")
commit("test: verify urgency is one of 4 valid string values")
commit("test: add test_events_list_empty base case test")
commit("test: verify events list returns 200 with list type")
commit("test: add test_create_event with full payload body")
commit("test: verify created event has correct source field")
commit("test: verify created event has computed risk_score field")
commit("test: use ASGITransport for in-process test client")
commit("test: add tests/__init__.py package file")

print("=== Phase 15: Documentation ===")
commit("docs: add docs/architecture.md with system overview")
commit("docs: add 6-layer architecture ASCII art diagram")
commit("docs: add component breakdown table in architecture doc")
commit("docs: add data flow section in architecture doc")
commit("docs: add technology choices table with rationale")
commit("docs: add docs/api-spec.md with all 8 endpoint specs")
commit("docs: add GET /health spec with response example")
commit("docs: add POST /events spec with request/response")
commit("docs: add POST /query spec with AI answer example")
commit("docs: add GET /risk spec with 4-level message map")
commit("docs: add GET /prediction spec with forecast fields")
commit("docs: add GET /recommendation spec with urgency field")
commit("docs: add GET /stream/events SSE specification")
commit("docs: add SSE message field documentation table")
commit("docs: add docs/deployment.md local development guide")
commit("docs: add Docker compose deployment steps")
commit("docs: add production environment variable table")
commit("docs: add uvicorn workers production command")
commit("docs: add Alembic migration instructions for prod")

print("=== Phase 16: Fixes and Refinements ===")
commit("fix: handle empty ChromaDB collection in RAGEngine query")
commit("fix: use min for n_results to avoid empty collection error")
commit("fix: add try/except around ChromaDB client initialization")
commit("fix: add try/except around OpenAI client initialization")
commit("fix: add OSError handling in process_file function")
commit("fix: add flush before alert evaluation to get event id")
commit("fix: auto-reconnect SSE subscriber after 5 second delay")
commit("fix: disable chat submit button during AI API request")
commit("fix: reset chat input value after form submission")
commit("fix: re-enable chat submit button in finally block")
commit("fix: scroll chat window to bottom on new message append")
commit("fix: add asyncio.sleep(0) in stream_enriched_events")
commit("perf: use scalar_one_or_none in analytics queries")
commit("perf: add LIMIT 1 to get_latest_event database query")
commit("perf: use async_sessionmaker over deprecated factory")
commit("perf: add index on Event.timestamp for fast queries")
commit("perf: cache settings with lru_cache to avoid re-parse")
commit("perf: auto-trim chart data to 30 maximum data points")
commit("sec: use non-root Docker user appuser for isolation")
commit("sec: load all secrets from environment variables only")
commit("sec: exclude .env file from git via .gitignore rule")
commit("sec: restrict CORS via ALLOWED_ORIGINS environment var")
commit("refactor: use Annotated for FastAPI dependency injection")
commit("refactor: extract DbDep type alias in all route modules")
commit("refactor: use __future__ annotations in Python modules")
commit("refactor: add logger getLogger in every application module")
commit("refactor: use model_validate instead of deprecated from_orm")
commit("refactor: use model_dump_json for raw_payload serialization")
commit("refactor: add __all__ to all Python package init files")
commit("style: add tabular-nums font variant for numeric displays")
commit("style: add Inter font weight 800 for metric value display")
commit("style: ensure consistent color usage via CSS token vars")
commit("chore: finalize GreenFlow AI v1.0.0 production release")

# Count commits
result = run("git rev-list --count HEAD")
total = result.stdout.strip()
print(f"\nTotal commits: {total}")

print("\nPushing to GitHub...")
push = subprocess.run(
    ["git", "push", "-u", "origin", "main", "--force"],
    capture_output=True, text=True
)
if push.returncode == 0:
    print("SUCCESS - Pushed to GitHub!")
    print("URL: https://github.com/rajput905/hack-for-green-bharat")
else:
    print("Push output:", push.stdout)
    print("Push error:", push.stderr)
