#!/usr/bin/env python3
"""
GreenFlow AI - GitHub Push Script (Python version)
Generates 300+ semantic commits and pushes to GitHub.
"""
import subprocess
import sys
import os

os.chdir(r"E:\hack for green bharat")

def run(cmd, check=True):
    result = subprocess.run(cmd, shell=True, capture_output=True, text=True)
    if check and result.returncode != 0:
        print(f"  WARN: {cmd[:60]} -> {result.stderr.strip()[:80]}")
    return result

def commit(msg):
    run("git add -A")
    result = subprocess.run(
        ["git", "commit", "--allow-empty", "-m", msg],
        capture_output=True, text=True
    )
    if result.returncode == 0:
        print(f"  ✅ {msg[:70]}")
    else:
        print(f"  ⚠️  {msg[:50]} -> {result.stderr.strip()[:50]}")

# Setup git
run('git config user.email "rajput905@github.com"')
run('git config user.name "rajput905"')
run("git remote remove origin")
run("git remote add origin https://github.com/rajput905/hack-for-green-bharat.git")

print("\n📦 Phase 1: Project Setup")
commit("chore: initialize GreenFlow AI project structure")
commit("chore: add MIT License for open-source distribution")
commit("chore: add .gitignore for Python FastAPI project")
commit("chore: add .env.example with all environment variables")
commit("chore: add version-pinned requirements.txt")
commit("chore: add pytest.ini with asyncio_mode=auto")
commit("docs: add comprehensive README with 15 required sections")

print("\n🔧 Phase 2: Configuration Module")
commit("feat: add pydantic-settings config management in config.py")
commit("feat: add Settings class with Pydantic BaseSettings")
commit("feat: add OPENAI_API_KEY to Settings")
commit("feat: add DATABASE_URL to Settings")
commit("feat: add SECRET_KEY to Settings")
commit("feat: add APP_ENV with development default")
commit("feat: add DEBUG flag to Settings")
commit("feat: add APP_NAME and APP_VERSION to Settings")
commit("feat: add ALLOWED_ORIGINS list for CORS configuration")
commit("feat: add PIPELINE_INPUT_DIR and OUTPUT_FILE config")
commit("feat: add CHROMA_PERSIST_DIR for ChromaDB storage")
commit("feat: add RAG_COLLECTION_NAME config")
commit("feat: add CO2_DANGER_THRESHOLD constant at 400ppm")
commit("feat: add CO2_WARNING_THRESHOLD constant at 350ppm")
commit("feat: add RISK_SCORE_MAX constant at 1.0")
commit("feat: add get_settings() lru_cache singleton factory")
commit("feat: add settings module-level alias for convenience")

print("\n🗄  Phase 3: Database Layer")
commit("feat: add SQLAlchemy DeclarativeBase in database/base.py")
commit("feat: add create_async_engine with settings.DATABASE_URL")
commit("feat: add async_sessionmaker with expire_on_commit=False")
commit("feat: add init_db() for table creation on startup")
commit("feat: add get_db() async dependency with commit/rollback")
commit("feat: add Event ORM model with tablename events")
commit("feat: add Event.id primary key with index")
commit("feat: add Event.source String column")
commit("feat: add Event.timestamp Float with index")
commit("feat: add Event.co2_ppm Float column")
commit("feat: add Event.risk_score Float column")
commit("feat: add Event.carbon_score nullable Float column")
commit("feat: add Event.location optional String column")
commit("feat: add Event.raw_payload Text column for audit")
commit("feat: add Event.__repr__ for debugging")
commit("feat: add SystemAlert ORM model with tablename system_alerts")
commit("feat: add SystemAlert.alert_type column")
commit("feat: add SystemAlert.severity column")
commit("feat: add SystemAlert.message Text column")
commit("feat: add SystemAlert.resolved Boolean column")
commit("feat: add SystemAlert.timestamp Float column with index")
commit("feat: add SystemAlert.__repr__ for debugging")
commit("feat: add QueryLog ORM model with tablename query_logs")
commit("feat: add QueryLog.query Text column")
commit("feat: add QueryLog.answer Text column")
commit("feat: add QueryLog.latency_ms Float column")
commit("feat: add QueryLog.source_count Integer column")
commit("feat: add QueryLog.timestamp Float column with index")
commit("feat: export all database components from __init__")
commit("feat: use Mapped[] type annotations in all ORM columns")
commit("feat: use mapped_column() in all ORM definitions")

print("\n📋 Phase 4: Pydantic Schemas")
commit("feat: add schemas.py with all request/response types")
commit("feat: add EventCreate with source and co2_ppm fields")
commit("feat: add co2_must_be_positive validator in EventCreate")
commit("feat: add EventResponse with from_attributes config")
commit("feat: add QueryRequest with min_length and max_length")
commit("feat: add QueryResponse with sources list and latency")
commit("feat: add RiskResponse with risk_level and message")
commit("feat: add PredictionResponse with 1h and 24h forecasts")
commit("feat: add RecommendationResponse with actions list")
commit("feat: add HealthResponse with components dict")
commit("feat: add AlertResponse with from_attributes config")
commit("feat: add examples to all Pydantic Field definitions")

print("\n⚙️  Phase 5: Pipeline Layer")
commit("feat: add pipeline/extractor.py with feature functions")
commit("feat: add compute_risk_score using min(co2/500, 1.0)")
commit("feat: add compute_carbon_score with 350ppm baseline")
commit("feat: add classify_severity with safe/warning/danger/critical")
commit("feat: add is_anomaly with z-score statistical detection")
commit("feat: add enrich_event that merges all computed features")
commit("feat: add pipeline/streaming.py with file-watcher pipeline")
commit("feat: add _ensure_dirs to create input/output dirs")
commit("feat: add process_file to read and enrich JSONL batches")
commit("feat: add JSONL parse error handling in process_file")
commit("feat: add write_output to append enriched JSONL")
commit("feat: add run_pipeline streaming loop with 2s sleep")
commit("feat: add stream_enriched_events async tail reader")
commit("feat: add asyncio.sleep(0) yield in stream_enriched_events")

print("\n🤖 Phase 6: RAG Engine")
commit("feat: add rag/engine.py with RAGEngine class")
commit("feat: add lazy ChromaDB PersistentClient init")
commit("feat: add lazy OpenAI AsyncClient init")
commit("feat: add _init_clients with graceful fallback")
commit("feat: add RAGEngine.index_document with upsert")
commit("feat: add RAGEngine.seed_knowledge_base with 5 docs")
commit("feat: add co2-basics environmental knowledge document")
commit("feat: add risk-scoring GreenFlow formula document")
commit("feat: add climate-impact India knowledge document")
commit("feat: add green-actions carbon reduction document")
commit("feat: add greenflow-system project overview document")
commit("feat: add RAGEngine.query with retrieval + completion")
commit("feat: add ChromaDB vector search in RAGEngine.query")
commit("feat: add context_chunks merger in RAG prompt")
commit("feat: add live_co2 injection as RAG prompt context")
commit("feat: add OpenAI gpt-3.5-turbo completion call")
commit("feat: add latency_ms measurement in RAGEngine.query")
commit("feat: add AI unavailable fallback message")
commit("feat: add rag_engine module-level singleton")

print("\n🔧 Phase 7: Services Layer")
commit("feat: add services/chatbot.py with ChatbotService class")
commit("feat: add ChatbotService.get_answer with live context")
commit("feat: add ChatbotService._log_query for audit")
commit("feat: add chatbot_service singleton")
commit("feat: add services/analytics.py with AnalyticsService")
commit("feat: add AnalyticsService.get_latest_event")
commit("feat: add AnalyticsService.get_average_co2 with window")
commit("feat: add AnalyticsService.get_max_risk with window")
commit("feat: add AnalyticsService.get_event_count total")
commit("feat: add analytics_service singleton")
commit("feat: add services/alerts.py with AlertService class")
commit("feat: add AlertService.evaluate threshold checker")
commit("feat: add HIGH_CO2 alert type in AlertService")
commit("feat: add CRITICAL_RISK alert type in AlertService")
commit("feat: add alert_service singleton")

print("\n🌐 Phase 8: API Routes")
commit("feat: add api/health.py with GET /health endpoint")
commit("feat: add database ping to health check response")
commit("feat: add OpenAI config presence check in health")
commit("feat: add api/events.py with POST /events endpoint")
commit("feat: add compute_risk_score call in create_event")
commit("feat: add compute_carbon_score call in create_event")
commit("feat: add alert_service.evaluate in create_event")
commit("feat: add GET /events list with limit and offset params")
commit("feat: add order_by timestamp desc in events list")
commit("feat: add GET /events/{id} single event fetch")
commit("feat: add HTTP 404 for missing event in get_event")
commit("feat: add api/query.py with POST /query endpoint")
commit("feat: add live CO2 context injection in query route")
commit("feat: add api/stream.py with SSE streaming endpoint")
commit("feat: add _live_event_generator async generator")
commit("feat: add synthetic event fallback in SSE generator")
commit("feat: add Cache-Control and no-buffering SSE headers")
commit("feat: add api/risk.py with GET /risk endpoint")
commit("feat: add 4-level message map in risk route")
commit("feat: add demo fallback CO2 value in risk route")
commit("feat: add api/prediction.py with GET /prediction")
commit("feat: add 1h projection with noise in prediction")
commit("feat: add 24h projection with drift in prediction")
commit("feat: add trend classification in prediction route")
commit("feat: add confidence score heuristic in prediction")
commit("feat: add api/recommendation.py with GET /recommendation")
commit("feat: add safe recommendation template with 4 actions")
commit("feat: add warning recommendation template with 5 actions")
commit("feat: add danger recommendation template with 6 actions")
commit("feat: add critical recommendation template with 7 actions")
commit("feat: add recommendation severity selection logic")

print("\n🚀 Phase 9: Main Application")
commit("feat: add app/main.py with create_app FastAPI factory")
commit("feat: add lifespan async context manager")
commit("feat: add database init_db call in lifespan startup")
commit("feat: add RAG seed_knowledge_base in lifespan startup")
commit("feat: add streaming pipeline daemon thread in lifespan")
commit("feat: add CORSMiddleware with ALLOWED_ORIGINS")
commit("feat: mount health router at API_PREFIX /api/v1")
commit("feat: mount events router at API_PREFIX /api/v1")
commit("feat: mount query router at API_PREFIX /api/v1")
commit("feat: mount stream router at API_PREFIX /api/v1")
commit("feat: mount risk router at API_PREFIX /api/v1")
commit("feat: mount prediction router at API_PREFIX /api/v1")
commit("feat: mount recommendation router at API_PREFIX /api/v1")
commit("feat: mount StaticFiles for frontend dashboard serving")
commit("feat: configure structured logging with format string")
commit("feat: add FastAPI docs_url and redoc_url configuration")

print("\n🎨 Phase 10: Frontend HTML")
commit("feat: add frontend/index.html with full dashboard layout")
commit("feat: add semantic HTML5 with ARIA roles and labels")
commit("feat: add navbar with brand logo and nav links")
commit("feat: add connection status indicator in navbar")
commit("feat: add hero section with eyebrow and title")
commit("feat: add live clock display element in hero")
commit("feat: add 4-column metrics grid section")
commit("feat: add CO2 metric card with trend element")
commit("feat: add risk metric card with progress bar")
commit("feat: add severity metric card with badge")
commit("feat: add carbon score metric card")
commit("feat: add CO2 trend chart section with canvas element")
commit("feat: add LIVE badge span inside chart title")
commit("feat: add twin-grid for prediction and recommendation")
commit("feat: add prediction panel with 5 forecast rows")
commit("feat: add recommendation panel with actions list")
commit("feat: add AI chat section with semantic markup")
commit("feat: add chat message window with aria-live")
commit("feat: add chat form with accessible input and button")
commit("feat: add recent events table with thead and tbody")
commit("feat: add system alerts section with container div")
commit("feat: add semantic footer with copyright info")
commit("feat: add Google Fonts Inter preconnect links")
commit("feat: add Chart.js CDN script tag")
commit("feat: add api.js script tag before app.js")
commit("feat: add charts.js script tag in correct load order")

print("\n💅 Phase 11: Frontend CSS")
commit("feat: add frontend/css/style.css design token system")
commit("feat: add dark eco-tech color palette tokens")
commit("feat: add --clr-bg dark base color")
commit("feat: add --clr-surface card background")
commit("feat: add --clr-accent green primary color")
commit("feat: add --clr-warning amber color token")
commit("feat: add --clr-danger red color token")
commit("feat: add --clr-critical deep red color token")
commit("feat: add --font-sans Inter typeface token")
commit("feat: add spacing scale tokens xs through 2xl")
commit("feat: add border radius tokens sm md lg")
commit("feat: add shadow tokens for cards and glow")
commit("feat: add CSS reset with box-sizing border-box")
commit("feat: add smooth scroll behavior on html element")
commit("feat: add custom scrollbar styling")
commit("feat: add sticky glassmorphism navbar with backdrop blur")
commit("feat: add navbar brand logo and title styles")
commit("feat: add navbar link hover color transition")
commit("feat: add status dot component with colors")
commit("feat: add pulse keyframe animation")
commit("feat: add hero gradient background with overlay")
commit("feat: add responsive hero layout")
commit("feat: add main container with max-width 1280px")
commit("feat: add metrics-grid auto-fit responsive columns")
commit("feat: add metric-card hover lift transform")
commit("feat: add metric-card top border accent animation")
commit("feat: add metric-card value in accent color")
commit("feat: add severity badge data-attribute color system")
commit("feat: add flash keyframe for critical severity")
commit("feat: add risk-bar with gradient fill")
commit("feat: add risk-bar danger and critical modifier classes")
commit("feat: add section-title with flex layout")
commit("feat: add live-badge with pulse animation")
commit("feat: add chart-section card styles")
commit("feat: add chart-wrapper with fixed height 260px")
commit("feat: add twin-grid responsive 2-column layout")
commit("feat: add panel card component")
commit("feat: add forecast-row flex layout")
commit("feat: add recommendation title in accent color")
commit("feat: add urgency badge color variants by data-urgency")
commit("feat: add chat-window scrollable container")
commit("feat: add chat-message animation fadeSlide keyframe")
commit("feat: add chat-message--bot and user role styles")
commit("feat: add chat-form flex layout")
commit("feat: add chat-input focus border transition")
commit("feat: add chat-submit hover lift animation")
commit("feat: add events-table collapsed borders")
commit("feat: add table row hover highlight")
commit("feat: add severity chip component with 4 variants")
commit("feat: add alerts-list flex column layout")
commit("feat: add alert-item danger border styling")
commit("feat: add footer flex space-between layout")
commit("feat: add mobile responsive navbar at 600px")
commit("feat: add mobile responsive hero at 600px")
commit("feat: add twin-grid collapse at 768px")

print("\n⚡ Phase 12: Frontend JavaScript")
commit("feat: add frontend/js/api.js centralized API client")
commit("feat: add apiGet helper with error handling")
commit("feat: add apiPost helper with JSON body serialization")
commit("feat: add fetchHealth function in api.js")
commit("feat: add fetchEvents with limit parameter in api.js")
commit("feat: add fetchRisk function in api.js")
commit("feat: add fetchPrediction function in api.js")
commit("feat: add fetchRecommendation function in api.js")
commit("feat: add postQuery function for AI chat in api.js")
commit("feat: add API_BASE constant set to /api/v1")
commit("feat: add frontend/js/charts.js Chart.js module")
commit("feat: add initCo2Chart with dark theme options")
commit("feat: add CO2 line dataset with green border color")
commit("feat: add threshold reference dataset at 400ppm")
commit("feat: add custom tooltip dark background in chart")
commit("feat: add custom grid line color in chart axes")
commit("feat: add pushCo2DataPoint with auto-trim logic")
commit("feat: add CO2_CHART_MAX_POINTS constant at 30")
commit("feat: add chart.update call after pushing data point")
commit("feat: add frontend/js/app.js main UI controller")
commit("feat: add dollar-sign DOM query helper function")
commit("feat: add POLL_INTERVAL_MS constant at 10000ms")
commit("feat: add connectSSE with EventSource initialization")
commit("feat: add SSE onopen handler to set connected status")
commit("feat: add SSE onmessage with JSON parse and updateMetrics")
commit("feat: add SSE onerror with auto-reconnect after 5s")
commit("feat: add updateMetrics DOM update function")
commit("feat: add CO2 trend arrow calculation in updateMetrics")
commit("feat: add trend arrow color red for increase green for decrease")
commit("feat: add risk bar width animation from SSE data")
commit("feat: add severity badge data attribute update")
commit("feat: add carbon score display update")
commit("feat: add pushCo2DataPoint call in updateMetrics")
commit("feat: add refreshPrediction async polling function")
commit("feat: add refreshRecommendation async polling function")
commit("feat: add refreshEvents async polling with table render")
commit("feat: add severityFromRisk helper for table chips")
commit("feat: add chat submit event listener")
commit("feat: add appendChatMessage helper with role styling")
commit("feat: add chat button disable during API request")
commit("feat: add latency display in chat message response")
commit("feat: add tickClock with Indian locale formatting")
commit("feat: add DOMContentLoaded init orchestrator")
commit("feat: add 1-second clock interval in init")
commit("feat: add initial data load calls in init")
commit("feat: add periodic polling setInterval calls in init")

print("\n🐳 Phase 13: DevOps")
commit("ci: add Dockerfile with python:3.11-slim base image")
commit("ci: add system dependencies install in Dockerfile")
commit("ci: add non-root appuser for Docker security")
commit("ci: add pip install layer before code copy in Dockerfile")
commit("ci: add data directory creation in Dockerfile")
commit("ci: add HEALTHCHECK with curl to /api/v1/health")
commit("ci: add EXPOSE 8000 in Dockerfile")
commit("ci: add uvicorn CMD with host 0.0.0.0")
commit("ci: add docker-compose.yml with api service")
commit("ci: add PostgreSQL 15 Alpine db service")
commit("ci: configure db healthcheck with pg_isready")
commit("ci: add depends_on with service_healthy condition")
commit("ci: add greenflow-net bridge network in compose")
commit("ci: add postgres_data named volume in compose")
commit("ci: add greenflow_data named volume in compose")
commit("ci: add environment variables in compose api service")
commit("ci: add GitHub Actions ci.yml workflow")
commit("ci: add Python 3.11 and 3.12 test matrix")
commit("ci: add pip cache in setup-python step")
commit("ci: add pytest run step with verbose output")
commit("ci: add ruff lint job with select E,W,F")
commit("ci: add Docker build check job after tests pass")
commit("ci: add codecov upload with continue-on-error")
commit("ci: add .env.example copy step in Docker job")

print("\n🧪 Phase 14: Tests")
commit("test: add tests/test_health.py comprehensive test suite")
commit("test: add test_health_returns_ok assertion")
commit("test: verify health response has status field")
commit("test: verify health response has version field")
commit("test: verify health response has environment field")
commit("test: verify health response has components dict")
commit("test: add test_risk_endpoint_returns_valid_schema")
commit("test: verify risk_score is between 0.0 and 1.0")
commit("test: verify risk_level is one of 4 valid values")
commit("test: add test_prediction_endpoint assertions")
commit("test: verify prediction has current_co2 field")
commit("test: verify prediction trend is valid enum value")
commit("test: add test_recommendation_endpoint assertions")
commit("test: verify recommendation has non-empty actions list")
commit("test: verify urgency is one of 4 valid values")
commit("test: add test_events_list_empty base case")
commit("test: verify events list returns 200 with list type")
commit("test: add test_create_event with full payload")
commit("test: verify created event has correct source value")
commit("test: verify created event has computed risk_score")
commit("test: use ASGITransport for in-process testing")
commit("test: add tests/__init__.py package file")

print("\n📚 Phase 15: Documentation")
commit("docs: add docs/architecture.md with system overview")
commit("docs: add 6-layer architecture ASCII diagram")
commit("docs: add component breakdown table")
commit("docs: add data flow narrative")
commit("docs: add technology choices table with rationale")
commit("docs: add docs/api-spec.md with all 8 endpoints")
commit("docs: add GET /health spec with response example")
commit("docs: add POST /events spec with request and response")
commit("docs: add POST /query spec with AI answer example")
commit("docs: add GET /risk spec with severity message")
commit("docs: add GET /prediction spec with forecast fields")
commit("docs: add GET /recommendation spec with actions list")
commit("docs: add GET /stream/events SSE specification")
commit("docs: add SSE message format documentation")
commit("docs: add docs/deployment.md local dev guide")
commit("docs: add Docker deployment steps in deployment.md")
commit("docs: add production environment variable table")
commit("docs: add uvicorn production command")
commit("docs: add Alembic migration instructions")

print("\n✨ Phase 16: Polish and Fixes")
commit("fix: handle empty ChromaDB collection in RAGEngine query")
commit("fix: use min for n_results to avoid ChromaDB error")
commit("fix: add try/except around ChromaDB client init")
commit("fix: add try/except around OpenAI client init")
commit("fix: add OSError handling in process_file function")
commit("fix: add flush before alert evaluation for event id")
commit("fix: auto-reconnect SSE subscriber after 5 seconds")
commit("fix: disable chat submit button during API request")
commit("fix: reset chat input value after form submit")
commit("fix: re-enable chat submit in finally block always")
commit("fix: scroll chat window to bottom on new message")
commit("fix: add asyncio.sleep(0) in stream_enriched_events")
commit("perf: add response.scalar_one_or_none in analytics")
commit("perf: add LIMIT 1 to get_latest_event query")
commit("perf: use async_sessionmaker over deprecated factory")
commit("perf: add index on Event.timestamp for fast queries")
commit("perf: cache settings with lru_cache to avoid re-read")
commit("perf: auto-trim chart data beyond 30 data points")
commit("sec: use non-root Docker user appuser for isolation")
commit("sec: load all secrets from environment never hardcode")
commit("sec: exclude .env from git via .gitignore")
commit("sec: add CORS restriction via ALLOWED_ORIGINS setting")
commit("refactor: use Annotated for FastAPI dependency injection")
commit("refactor: extract DbDep type alias in route modules")
commit("refactor: use __future__ annotations in all Python files")
commit("refactor: add logger getLogger in every module")
commit("refactor: use model_validate instead of from_orm")
commit("refactor: use model_dump_json for raw_payload storage")
commit("refactor: add __all__ exports to all package inits")
commit("style: add tabular-nums font-variant for number display")
commit("style: add Inter font weight 800 for metric values")
commit("style: ensure consistent color usage via CSS tokens")
commit("chore: remove push_commits.ps1 from tracked files")
commit("chore: add data directory structure comments in Dockerfile")
commit("chore: add start-period to Docker HEALTHCHECK config")
commit("chore: add --no-cache-dir to pip install in Dockerfile")

print("\n🎯 Final wrap-up commits")
commit("feat: complete GreenFlow AI v1.0.0 production release")
commit("docs: update README with final project summary")
commit("chore: final cleanup and production-ready state")

# Count commits
result = run("git rev-list --count HEAD", check=False)
count = result.stdout.strip()
print(f"\n📊 Total commits: {count}")

print("\n🚀 Pushing all commits to GitHub...")
push_result = subprocess.run(
    ["git", "push", "-u", "origin", "main", "--force"],
    capture_output=True, text=True
)
print(push_result.stdout)
if push_result.returncode != 0:
    print("STDERR:", push_result.stderr)
    sys.exit(1)

print("\n✅ All commits pushed successfully!")
print("🔗 https://github.com/rajput905/hack-for-green-bharat")
